server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: 
        uri:
        predicates:
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defailtZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    